version: '3.9'
services:
  # Backend (Laravel)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: backend
    container_name: contacts_app_backend
    restart: unless-stopped
    working_dir: /var/www/html/backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=contacts
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - APP_KEY=
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      ##- MIX_APP_URL="${APP_URL}"
      ##- MIX_SOCKET_URL="${APP_URL}"
    depends_on:
      - db
    networks:
      - contacts_network

  # Frontend (Vue.js)
  frontend:
    build:
      context: . 
      dockerfile: frontend/Dockerfile
    image: frontend
    container_name: contacts_app_frontend
    restart: unless-stopped
    working_dir: /var/www/html/frontend
    environment:
      - VUE_APP_API_URL=http://app:8000/api
    ports:
      - "8080:8080"
    networks:
      - contacts_network

  # Database (postgres)
  db:
    image: postgres:14.1-alpine
    container_name: contacts_app_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contacts
    ports:
      - "5432:5432"
    networks:
      - contacts_network
volumes:
  data:
    driver: local
networks:
  contacts_network:
    driver: bridge
